### PR TITLE
Adds theme, name and version to options

### PR DESCRIPTION
**Pull request by davehg**
Current version does not support theme configuration.

### CODE REVIEW

**Comment by jtorresfabra** [comment]
Hey @SunboX, any chance you can review this patch? It is very useful, otherwise It is not clear how to apply a theme.

**Comment by SunboX** [comment]
jep, I'm a bit bussy. Maybe later this day

**Comment by jtorresfabra** [comment]
great thanks! :+1:

**Comment by SunboX** [comment]
Hey, sry hadn't the time by now! :cry:  I will look into it as soon as I get the time to. I'm on vecation next week and I don't know if I get the time before.

**Comment by SunboX** [comment]
Hey @davehg I've merged it and added a demo/test case for it. Thanks for contributing! ❤️

**Pull request merged**
